# Sample Config

# Git program to use
git-program: lazygit

# GitHub username
github-username: yourusername

# List of repositories
repos:
  - name: Dotfiles
    path: /Users/yourusername/Dotfiles/
    fav:  false
