# Sample Config

# Git program to use
git-program: lazygit

# GitHub username
github-username: yourusername

# List of repositories
repos:
  - name: Dotfiles
    path: /Users/yourusername/Dotfiles/
    fav:  false
  - name: Project1
    path: /Users/yourusername/Project1/
  - name: Project2
    path: /Users/yourusername/Project2/
    fav:  true
